[package]
name = "nail"
version = "0.1.0"
authors = ["Max Hunt <max@huntw3.com>"]
autobins = false
edition = "2018"

[dependencies]
num = "0.2"
regex = "1"

[lib]
name = "nail"
path = "src/lib.rs"

[[bin]]
name = "nailc"
path = "src/main.rs"

[features]
debugTraceExecution = []
